type: google.api.Service
config_version: 3

http:
    rules:
        - selector: tweet.TweetService.ListTweets
          get: /v1/tweet
        # - selector: collection.CollectionService.Update
        #   patch: /v1/collection/{data.id}
        #   body: "*"
        - selector: tweet.TweetService.GetTweet
          get: /v1/tweet/{tweet_id}
          response_body: tweet
