type: google.api.Service
config_version: 3

http:
    rules:
        - selector: tag.TagService.FindOrCreate
          post: /v1/tag1
          body: "tag11"
        # - selector: collection.CollectionService.Update
        #   patch: /v1/collection/{data.id}
        #   body: "*"
