type: google.api.Service
config_version: 3

http:
    rules:
        - selector: profile.ProfileService.Find
          get: /v1/profile
          #body: "*"
        # - selector: collection.CollectionService.Update
        #   patch: /v1/collection/{data.id}
        #   body: "*"
